# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "/wai-about-wai" # the subpath of your site, e.g. /blog
url: "https://w3c.github.io" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-about-wai

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

remote_theme: w3c/wai-website-theme

collections:
  about:
    area: "About WAI"
    name: "About WAI"
    shortname: "About WAI"
    # icon: "book" # TODO
    repostitory: w3c/wai-about-wai
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
    parent: "/"
    navigation:
      name: About WAI
      url: "/about/"
      pages:
      - name: About WAI
        url: "/about/"
      - name: Participating
        url: "/about/participating/"
      - name: Translating
        url: "/about/translating/"
      - name: Contacting
        url: "/about/contacting/"
      - name: Sponsoring
        url: "/about/sponsoring/"
      - name: Projects
        url: "/about/projects/"
        pages:
        - name: WAI-Tools
          url: "/about/projects/wai-tools/"
          pages:
          - name: Online Symposium
            url: "/about/projects/wai-tools/symposium/"
            pages:
            - name: Record
              url: "/about/projects/wai-tools/symposium/record/"
          - name: First Open Meeting
            url: "/about/projects/wai-tools/first-open-meeting/"
        - name: Evaluation and Report Language – EARL
          url: "/standards-guidelines/earl/"
      - name: Groups
        url: "/about/groups/"
        pages:
        - name: 'AGWG: Accessibility Guidelines <abbr title="Working Group">WG</abbr>'
          url: "https://www.w3.org/WAI/GL/"
        - name: 'APA: Accessible Platform <abbr title="Working Group">WG</abbr>'
          url: "https://www.w3.org/WAI/APA/"
        - name: 'ARIA: Accessible Rich Internet Applications <abbr title="Working Group">WG</abbr>'
          url: "https://www.w3.org/WAI/ARIA/"
        - name: 'EOWG: Education and Outreach <abbr title="Working Group">WG</abbr>'
          url: "/about/groups/eowg/"
        - name: 'WAI IG: WAI Interest Group'
          url: "/about/groups/waiig/"
        - name: 'Group Task Forces'
          url: "/about/groups/taskforces/"

defaults:
  -
    scope:
      path: "_about"
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-remote-theme
